### ISSUE TITLE
minijson_reader does not reject unescaped control characters in strings

### ISSUE THREAD

**Issue by michaelkourlas** [giacomodrago/minijson_reader#31]
Per RFC 8259, the control characters 0x01 to 0x1F must be escaped if they appear in JSON strings.

> unescaped = %x20-21 / %x23-5B / %x5D-10FFFF

I will submit a PR shortly with a simple fix.

**Comment by michaelkourlas** [comment]
Here's the PR: https://github.com/giacomodrago/minijson_reader/pull/32

**Comment by giacomodrago** [comment]
Merged with thanks.

To be honest, I am not entirely sure whether we have 100% compliance with the RFC and I should do a full audit. For starters, you yourself made `U+0000` illegal where it is OK as per the spec, but I so agree with your call, due to the fact that it maps to UTF-8 `0x00`, which is the same as ASCII null, which has a special historical meaning in C, and we'll never fully get rid of that.
